### ISSUE TITLE
--no-rdoc in .rvmrc is ignored

### ISSUE THREAD

**Issue by ifel** [MurgaNikolay/chef-rvm#7]
The cookbook's default['chef_rvm']['rvmrc']['rvm_gem_options'] is '--no-rdoc --no-ri'. It writes this variable to the ~/.rvmrc. It works fine. However, when one tries to install a gem into a gemset with the chef_rvm_gem provider, rdoc is still used. In my case, it fails on rdoc when I try to install cucumber version 1.1.9.

Please find the error below.

Honestly, I'm not RVM guru, I googled around and didn't find any clear recommendation to disable rdoc generation by adding rvm_gem_options to the ~/.rvmrc file. However, I found, and actually tested this, that it can be done by adding the following entries to the ~/.gemrc:

```
install: --no-rdoc --no-ri
update: --no-rdoc --no-ri
```

And mentions about new syntax:

```
install: --no-document
update: --no-document
```

Can you please check into this and decide how this can be fixed - by correcting .rvmrc, adding .gemrc or using another fix. If you want me to implement the fix, let me know, I will do and create a merge request.

```
  * chef_rvm_gem[rvm:gem:jenkins:1.9.3@:cucumber] action install

    ================================================================================
    Error executing action `install` on resource 'chef_rvm_gem[rvm:gem:jenkins:1.9.3@:cucumber]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of bash -c source\ /opt/jenkins_home/.rvm/scripts/rvm\;\ rvm\ 1.9.3@default\ do\ gem\ install\ cucumber\ -v\ 1.1.9 ----
    STDOUT: Building native extensions.  This could take a while...
    Successfully installed gherkin-2.9.3
    Successfully installed tins-1.5.4
    Successfully installed term-ansicolor-1.3.2
    Successfully installed builder-3.2.2
    Successfully installed diff-lcs-1.2.5

    (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

    Thank you for installing cucumber-1.1.9.
    Please be sure to read http://wiki.github.com/cucumber/cucumber/upgrading
    for important information about this release. Happy cuking!

    (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

    Successfully installed cucumber-1.1.9
    Installing ri documentation for gherkin-2.9.3
    STDERR: RDoc::Parser::Ruby failure around line 28 of
    tests/from_module_test.rb

    Before reporting this, could you check that the file you're documenting
    has proper syntax:

      /opt/jenkins_home/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -c tests/from_module_test.rb

    RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

    The internal error was:

        (NoMethodError) undefined method `name' for #<RDoc::RubyToken::TkASSIGN:0x0000000274b8a8>

    ERROR:  While executing gem ... (NoMethodError)
        undefined method `name' for #<RDoc::RubyToken::TkASSIGN:0x0000000274b8a8>
    ---- End output of bash -c source\ /opt/jenkins_home/.rvm/scripts/rvm\;\ rvm\ 1.9.3@default\ do\ gem\ install\ cucumber\ -v\ 1.1.9 ----
    Ran bash -c source\ /opt/jenkins_home/.rvm/scripts/rvm\;\ rvm\ 1.9.3@default\ do\ gem\ install\ cucumber\ -v\ 1.1.9 returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_rvm/libraries/rvm_simple_environment_gem.rb:17:in `gem_install'
    /var/chef/cache/cookbooks/chef_rvm/providers/gem.rb:18:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef_rvm/recipes/gems.rb

      8:       chef_rvm_gem "rvm:gem:#{username}:#{ruby_string}:#{resource_config['gem']}" do
      9:         user username
     10:         ruby_string ruby_string
     11:         gem resource_config['gem']
     12:         version resource_config['version'] if resource_config['version']
     13:         action resource_config['action'] if resource_config['action']
     14:       end
     15:     end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef_rvm/recipes/gems.rb:8:in `block (3 levels) in from_file'

    chef_rvm_gem("rvm:gem:jenkins:1.9.3@:cucumber") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_rvm_gem
      cookbook_name "chef_rvm"
      recipe_name "gems"
      user "jenkins"
      ruby_string "1.9.3@"
      gem "cucumber"
      version "1.1.9"
    end
```

**Comment by NikolayMurha** [comment]
https://github.com/rvm/rvm/blob/767fa24888fcf65e01b49c9a1e0fd811e48752c2/examples/rvmrc#L38
https://github.com/rvm/rvm/blob/bee47675c34a4ba96f849017ea06ce00efcbfc7a/scripts/functions/gemset#L171

You can pass --no-document to `rvm_gem_options`
